version: "3"
networks:
  kafka-net:
    driver: bridge
  janusgraph-network:
    driver: bridge

services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=janusgraph
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    ports:
      - "9042:9042"  # Cassandra default port
    networks:
      - janusgraph-network
    volumes:
      - cassandra-data:/var/lib/cassandra
      - cassandra-config:/etc/cassandra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTICSEARCH_USERNAME=myuser
      - ELASTICSEARCH_PASSWORD=mypassword
    ports:
      - "9200:9200"  # Elasticsearch default port
    networks:
      - janusgraph-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    environment:
      - storage.backend=cassandra
      - storage.hostname=cassandra
      - storage.port=9042
      - storage.cql.keyspace=mykeyspace
      - storage.cassandra.username=cassandra
      - storage.cassandra.password=cassandra
      - INDEX_BACKEND=elasticsearch
      - INDEX_HOSTNAME=elasticsearch
      - INDEX_ELASTICSEARCH_USER=myuser
      - INDEX_ELASTICSEARCH_PASSWORD=mypassword
      - JANUSGRAPH_MAX_HEAP_SIZE=1g
      - JAVA_OPTIONS=-Xms1G -Xmx2G
    ports:
      - "8182:8182"  # Gremlin Server default port
    networks:
      - janusgraph-network
    depends_on:
      - cassandra
      - elasticsearch
    volumes:
      - janusgraph-config:/janusgraph/config

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://52.19.2.233:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    extra_hosts:
      - "kafka:52.19.2.233"
    networks:
      - kafka-net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=fraud

volumes:
  cassandra-data:
  cassandra-config:
  elasticsearch-data:
  janusgraph-config:
