version: "3"
networks:
  kafka-net:
    driver: bridge

services:
  janusgraph:
    image: janusgraph/janusgraph:0.6.2
    container_name: janusgraph
    environment:
      - storage.backend=berkeleyje
      - storage.directory=/var/lib/janusgraph/db
      - JAVA_OPTIONS=-Xms1G -Xmx2G
    ports:
      - "8182:8182"
    volumes:
      - janusgraph-data:/var/lib/janusgraph/db



  gremlin-ui:
    image: prabushitha/gremlin-visualizer:latest
    container_name: gremlin-visualizer
    ports:
      - "3000:3000"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://52.19.2.233:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    extra_hosts:
      - "kafka:52.19.2.233"
    networks:
      - kafka-net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=fraud



volumes:
  janusgraph-data: