version: "3"
networks:
  kafka-net:
    driver: bridge

services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=janusgraph
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    ports:
      - "9042:9042"
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    environment:
      - storage.backend=cql
      - storage.hostname=cassandra
      - storage.cql.keyspace=janusgraph
      - JANUSGRAPH_MAX_HEAP_SIZE=1g
      - JAVA_OPTIONS=-Xms1G -Xmx2G
    ports:
      - "8182:8182"
    volumes:
      - janusgraph-data:/var/lib/janusgraph/db
    depends_on:
      - cassandra

  gremlin-ui:
    image: prabushitha/gremlin-visualizer:latest
    container_name: gremlin-visualizer
    ports:
      - "3000:3000"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://52.19.2.233:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    extra_hosts:
      - "kafka:52.19.2.233"
    networks:
      - kafka-net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=fraud

volumes:
  janusgraph-data:
