networks:
  janusgraph-network:
    driver: bridge

services:

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    ports:
      - "8182:8182"  # Gremlin Server default port
    networks:
      - janusgraph-network
    volumes:
      - ./janusgraph.properties:/opt/janusgraph/conf/janusgraph.properties

  gremlin-console:
    image: tinkerpop/gremlin-console:3.6.0
    container_name: gremlin-console
    depends_on:
      - janusgraph
    entrypoint: ["/bin/sh", "-c", "sleep 30; /opt/apache-tinkerpop-gremlin-console/bin/gremlin.sh"]
    networks:
      - janusgraph-network

volumes:
  janusgraph-config:
