networks:
  janusgraph-network:
    driver: bridge

services:

  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: janusgraph
    environment:
      - storage.backend=cassandra
      - storage.hostname=108.129.88.172
      - storage.batch-loading=true
      - storage.batch-size=5000
      - storage.buffer.size=8192
      - storage.transaction.batch.size=10000
      - storage.transaction.timeout=3660
      - graph.replace-instance-if-exists=true
      - storage.port=9042
      - storage.cql.keyspace=mykeyspace
      - storage.cassandra.username=cassandra
      - storage.cassandra.password=cassandra
      - cache.db-cache = true
      - cache.db-cache-clean-wait = 20
      - cache.db-cache-time = 180000
      - cache.db-cache-size = 0.25
      - index.search.backend=elasticsearch
      - index.search.hostname=108.129.88.172
      - index.search.elasticsearch.client-only=true
      - storage.directory=/var/lib/janusgraph/data
      - index.search.directory=/var/lib/janusgraph/index
      - INDEX_BACKEND=elasticsearch
      - INDEX_HOSTNAME=108.129.88.172
      - JANUSGRAPH_MAX_HEAP_SIZE=6g
      - JAVA_OPTIONS=-Xms8G -Xmx14G
    ports:
      - "8182:8182"  # Gremlin Server default port
    networks:
      - janusgraph-network
    volumes:
      - janusgraph-config:/janusgraph/config



volumes:
  janusgraph-config:
