networks:
  kafka-net:
    driver: bridge
  janusgraph-network:
    driver: bridge
  rabbitmq_go_net:
    driver: bridge

services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=janusgraph
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=4G
      - HEAP_NEWSIZE=4G
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    ports:
      - "9042:9042"  # Cassandra default port
    networks:
      - janusgraph-network
    volumes:
      - cassandra-data:/var/lib/cassandra
      - cassandra-config:/etc/cassandra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1G -Xmx2G
      - ELASTICSEARCH_USERNAME=myuser
      - ELASTICSEARCH_PASSWORD=mypassword
    ports:
      - "9200:9200"  # Elasticsearch default port
    networks:
      - janusgraph-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://localhost:9200"]'
      
volumes:
  cassandra-data:
  cassandra-config:
  elasticsearch-data:
  janusgraph-config:
